
DROP TABLE STATUS;
CREATE TABLE STATUS (
    STATUS_NO     NUMBER PRIMARY KEY, 
    STATUS_NAME   VARCHAR2(50) NOT NULL      
);

CREATE SEQUENCE SEQ_STATUS;

INSERT INTO STATUS (STATUS_NO, STATUS_NAME) VALUES (1, '할 일');
INSERT INTO STATUS (STATUS_NO, STATUS_NAME) VALUES (2, '진행 중');
INSERT INTO STATUS (STATUS_NO, STATUS_NAME) VALUES (3, '완료');

DROP SEQUENCE SEQ_TODO;
CREATE SEQUENCE SEQ_TODO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TODO (
    NO             VARCHAR2(20) PRIMARY KEY,     
    TITLE          VARCHAR2(200) NOT NULL,       
    CONTENT        VARCHAR2(1000),              
    STATUS_NO      NUMBER,                 
    DEL_YN         CHAR(1) DEFAULT 'N',          
    CREATED_DATE   DATE DEFAULT SYSDATE,         
    UPDATED_DATE   DATE,                         

    CONSTRAINT FK_TODO_STATUS
        FOREIGN KEY (STATUS_NO)
        REFERENCES STATUS (STATUS_NO)
);




INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE)
VALUES (SEQ_TODO.NEXTVAL, '장보기', '우유, 달걀, 식빵 구입', 1, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE)
VALUES (SEQ_TODO.NEXTVAL, '운동하기', '30분 러닝 AND 스트레칭', 2, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE)
VALUES (SEQ_TODO.NEXTVAL, '코딩 공부', 'Spring CRUD 기능 복습', 1, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE)
VALUES (SEQ_TODO.NEXTVAL, '친구 생일 선물 준비', '소소한 소품 구매 예정', 3, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE)
VALUES (SEQ_TODO.NEXTVAL, '책 읽기', '자바 ORM 표준 JPA 프로그래밍', 1, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '책 읽기', '자바 ORM 표준 JPA 프로그래밍', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '운동하기', '30분 러닝머신 + 스트레칭', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '강아지 산책', '아침에 공원 한 바퀴 돌기', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '스터디 자료 준비', '금요일 스터디 발표자료 PPT 만들기', 2, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '프로젝트 이슈 해결', '댓글 기능 오류 디버깅', 2, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '장 보기', '계란, 우유, 시리얼 사기', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '블로그 포스팅', 'Spring Pagination 정리글 작성', 3, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '이력서 수정', '경력사항 최신화', 2, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '친구 생일 선물', '기프티콘 보내기', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '세미나 참석', 'AWS 웨비나 오후 2시 참석', 2, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '영화 보기', '넷플릭스에서 미션 임파서블 보기', 3, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '메일 정리', '광고메일 정리 및 답장하기', 3, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '운전 연습', '시내 주행 30분 연습하기', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '알고리즘 문제 풀이', '백준 실버 2 문제 3개 풀기', 2, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, 'GitHub 정리', '레포 정리 및 README 업데이트', 3, 'N', SYSDATE);

INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '자기소개서 작성', '지원 기업용 맞춤 작성 시작', 2, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '회의 준비', '다음 주 회의 안건 정리', 2, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '집안일', '세탁기 돌리고 설거지하기', 1, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '캘린더 정리', '이번주 일정 Google Calendar에 정리', 3, 'N', SYSDATE);
INSERT INTO TODO (NO, TITLE, CONTENT, STATUS_NO, DEL_YN, CREATED_DATE) VALUES (SEQ_TODO.NEXTVAL, '노션 정리', '프로젝트 트래킹 페이지 구성하기', 2, 'N', SYSDATE);



commit;
